export const Roles = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
} as const;

export type RoleType = keyof typeof Roles;

export const Permissions = {
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  EDIT_WORKSPACE: "EDIT_WORKSPACE",
  MANAGE_WORKSPACE_SETTINGS: "MANAGE_WORKSPACE_SETTINGS",

  ADD_MEMBER: "ADD_MEMBER",
  CHANGE_MEMBER_ROLE: "CHANGE_MEMBER_ROLE",
  REMOVE_MEMBER: "REMOVE_MEMBER",

  CREATE_PROJECT: "CREATE_PROJECT",
  EDIT_PROJECT: "EDIT_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",

  CREATE_TASK: "CREATE_TASK",
  EDIT_TASK: "EDIT_TASK",
  DELETE_TASK: "DELETE_TASK",

  CREATE_COMMENT: "CREATE_COMMENT",
  EDIT_COMMENT: "EDIT_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",

  VIEW_ONLY: "VIEW_ONLY",

  UNDO_TASK: "UNDO_TASK",
  REDO_TASK: "REDO_TASK",

  CREATE_AUTOMATION: "CREATE_AUTOMATION",
  EDIT_AUTOMATION: "EDIT_AUTOMATION",
  DELETE_AUTOMATION: "DELETE_AUTOMATION",

  VIEW_ANALYTICS: "VIEW_ANALYTICS"
} as const;

export type PermissionType = keyof typeof Permissions;
